# Generated by Django 5.1.7 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='product1.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='product2.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='product3.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default='product4.jpg', upload_to='products/'),
        ),
    ]
