# Generated by Django 5.1.7 on 2025-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantee',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productscolor',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='guarantees',
            field=models.ManyToManyField(blank=True, to='product.guarantee'),
        ),
    ]
