# Generated by Django 5.1.7 on 2025-03-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_image_products_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='review',
            field=models.TextField(default='نقد بلند محصول'),
        ),
    ]
