# Generated by Django 5.1.7 on 2025-03-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productattribute_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_vots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
