# Generated by Django 5.1.7 on 2025-03-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='image',
        ),
    ]
