# Generated by Django 5.1.7 on 2025-03-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_image1_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscolor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.products'),
            preserve_default=False,
        ),
    ]
