# Generated by Django 5.1.7 on 2025-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_total_vots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
