# Generated by Django 5.1.7 on 2025-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productscolor_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_colored',
            field=models.BooleanField(default=True),
        ),
    ]
