# Generated by Django 5.1.7 on 2025-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_specialoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, to='product.productscolor'),
        ),
    ]
