# Generated by Django 5.1.7 on 2025-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_has_colored'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='category_images'),
        ),
    ]
