# Generated by Django 5.1.7 on 2025-03-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0008_compare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
