# Generated by Django 5.1.7 on 2025-04-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_compare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.png', upload_to='category_images'),
        ),
    ]
