# Generated by Django 5.1.8 on 2025-04-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
    ]
