# Generated by Django 5.1.7 on 2025-03-23 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16, validators=[django.core.validators.RegexValidator(message='شماره کارت باید 16 کارکتر عددی باشد', regex='^\\d{16}$')]),
        ),
    ]
