# Generated by Django 5.1.7 on 2025-03-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='location',
            new_name='province',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='receiver',
            field=models.CharField(default='خودم', max_length=50),
        ),
    ]
