# Generated by Django 5.1.7 on 2025-03-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_location_useraddress_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.province'),
        ),
    ]
