# Generated by Django 5.1.7 on 2025-03-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0004_rename_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='replay',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='replay',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
