# Generated by Django 5.1.7 on 2025-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at']},
        ),
    ]
