# Generated by Django 5.2 on 2025-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_hash',
            field=models.CharField(default='000000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_pan',
            field=models.CharField(default='000000000000000', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='ref_id',
            field=models.CharField(default='0000000000', max_length=30),
        ),
    ]
